### ISSUE TITLE
Tracking Income and Expenses

### ISSUE THREAD

**Issue by Benny-Nwaro** [Benny-Nwaro/Fash-Craft#9]
- [ ] Create UI for adding income and expense categories.
- [ ] Implement adding income transactions with source and amount.
- [ ] Develop UI to view and manage income transactions and categories.
- [ ] Implement adding expense transactions with category and amount.
- [ ] Develop UI to view and manage expense transactions and categories.
